# Generated by Django 5.2 on 2026-05-11 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='ชื่อห้อง')),
                ('temperature', models.FloatField(verbose_name='อุณหภูมิ (°C)')),
                ('humidity', models.FloatField(verbose_name='ความชื้น (%)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
