# Generated by Django 5.2 on 2025-08-13 07:10

import MRAapp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='เลขที่เอกสาร')),
                ('doc_date', models.DateField(default=django.utils.timezone.now, verbose_name='วัน/เดือน/ปี')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อเรื่อง')),
                ('file', models.FileField(blank=True, null=True, upload_to=MRAapp.models.document_upload_to, verbose_name='ไฟล์เอกสาร')),
                ('external_url', models.URLField(blank=True, verbose_name='ลิงก์ภายนอก')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
