# Generated by Django 5.2 on 2025-09-11 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn', models.CharField(blank=True, max_length=20, null=True, verbose_name='HN')),
                ('vn', models.CharField(blank=True, max_length=20, null=True, verbose_name='VN')),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ป่วย')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='วันที่มารับบริการ')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('total_score', models.IntegerField(default=0)),
                ('total_possible', models.IntegerField(default=0)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
