# Generated by Django 5.2 on 2025-08-13 09:18

import MRAapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(default=MRAapp.models.current_fiscal_year)),
                ('month', models.CharField(max_length=20)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('hn', models.CharField(blank=True, max_length=50, null=True)),
                ('an', models.CharField(blank=True, max_length=50, null=True)),
                ('hname', models.CharField(blank=True, max_length=255, null=True)),
                ('date_admitted', models.DateField(blank=True, null=True)),
                ('date_discharged', models.DateField(blank=True, null=True)),
                ('score_1', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('score_3', models.IntegerField(default=0)),
                ('score_4', models.IntegerField(default=0)),
                ('score_5', models.IntegerField(default=0)),
                ('score_6', models.IntegerField(default=0)),
                ('score_7', models.IntegerField(default=0)),
                ('score_8', models.IntegerField(default=0)),
                ('score_9', models.IntegerField(default=0)),
                ('score_10', models.IntegerField(default=0)),
                ('score_11', models.IntegerField(default=0)),
                ('score_12', models.IntegerField(default=0)),
                ('full_score', models.IntegerField(default=56)),
                ('sum_score', models.IntegerField(default=0)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
