# Generated by Django 5.2 on 2025-09-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0002_ipdcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='INPatientScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=20, verbose_name='Hcode')),
                ('hname', models.CharField(blank=True, max_length=255, verbose_name='Hname')),
                ('hn', models.CharField(blank=True, max_length=50, verbose_name='HN')),
                ('an', models.CharField(blank=True, max_length=50, verbose_name='AN')),
                ('date_admitted', models.DateField(blank=True, null=True, verbose_name='Date admitted')),
                ('date_discharged', models.DateField(blank=True, null=True, verbose_name='Date discharged')),
                ('s1', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s2', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s3', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s4', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s5', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s6', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s7', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s8', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s9', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s10', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s11', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('s12', models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3)),
                ('total_yes', models.PositiveIntegerField(default=0)),
                ('total_counted', models.PositiveIntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('title', models.CharField(default='แบบประเมินคุณภาพการดูแลผู้ป่วย (ชั่วคราว)', max_length=255, verbose_name='หัวข้อแบบประเมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
