# Generated by Django 5.2 on 2025-09-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0002_opdscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opdscore',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='opdscore',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='opdscore',
            name='vn',
        ),
        migrations.AddField(
            model_name='opdscore',
            name='audit_period',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ช่วงเวลาที่ตรวจสอบ (เดือน/ปี YYYY-MM)'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='1st Visit Date'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='hcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hcode'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='hname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hname'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='is_chronic',
            field=models.BooleanField(default=False, verbose_name='Chronic'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name='General'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='pid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PID'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='visit_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date (ถึง)'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='visit_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date (เริ่ม)'),
        ),
    ]
