# Generated by Django 5.2 on 2025-09-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0003_inpatientscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INPatientScore',
            new_name='PatientScore',
        ),
    ]
