# Generated by Django 5.2 on 2026-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0003_remove_opdscore_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='bonus_s1',
            field=models.IntegerField(choices=[(0, '0 (ปกติ)'), (1, '+1 (ดีเยี่ยม)'), (-1, '-1 (บกพร่อง)')], default=0, verbose_name='คะแนนพิเศษ หัวข้อ 1'),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='bonus_s12',
            field=models.IntegerField(choices=[(0, '0 (ปกติ)'), (1, '+1 (ดีเยี่ยม)'), (-1, '-1 (บกพร่อง)')], default=0, verbose_name='คะแนนพิเศษ หัวข้อ 12'),
        ),
    ]
