# Generated by Django 5.2 on 2026-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0004_patientscore_bonus_s1_patientscore_bonus_s12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscore',
            name='bonus_s1',
            field=models.IntegerField(choices=[(0, '0'), (1, '+1'), (-1, '-1')], default=0, verbose_name='คะแนนพิเศษ หัวข้อ 1'),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='bonus_s12',
            field=models.IntegerField(choices=[(0, '0'), (1, '+1'), (-1, '-1')], default=0, verbose_name='คะแนนพิเศษ หัวข้อ 12'),
        ),
    ]
