# Generated by Django 5.2 on 2025-09-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0004_rename_inpatientscore_patientscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='bonus_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='deduct_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s10',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s11',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s12',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='0', max_length=3),
        ),
    ]
