# Generated by Django 5.2 on 2025-09-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0005_patientscore_bonus_score_patientscore_deduct_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscore',
            name='s10',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s11',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s12',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
    ]
