# Generated by Django 5.2 on 2026-02-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0005_alter_patientscore_bonus_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdscore',
            name='is_psychiatric',
            field=models.BooleanField(default=False, verbose_name='Psychiatric'),
        ),
        migrations.AddField(
            model_name='opdscore',
            name='review_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Review Status'),
        ),
    ]
