# Generated by Django 5.2 on 2025-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0006_alter_patientscore_s10_alter_patientscore_s11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='final_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='max_score',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='bonus_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='deduct_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
