# Generated by Django 5.2 on 2026-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0006_opdscore_is_psychiatric_opdscore_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdscore',
            name='review_status',
            field=models.CharField(blank=True, choices=[('inadequate', 'Documenttation inadequate for meaningful review (ข้อมูลไม่เพียงพอสำหรับการทบทวน)'), ('no_issue', 'No significant medical recode issue identified (ไม่มีปัญหาสำคัญจากการทบทวน)'), ('has_issue', 'Certain issue in question specify (มีปัญหาจากการทบทวนที่ต้องค้นต่อ ระบุ)')], max_length=50, null=True, verbose_name='Review Status'),
        ),
    ]
