# Generated by Django 5.2 on 2025-09-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0007_patientscore_final_score_patientscore_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientscore',
            name='bonus_score',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='deduct_score',
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s10',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s11',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s12',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
    ]
