# Generated by Django 5.2 on 2026-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0007_alter_opdscore_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='certain_issue_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ระบุปัญหา (กรณีเลือก Certain issue)'),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='finding_no_id_issue',
            field=models.BooleanField(default=False, verbose_name='เอกสารบางแผ่น ไม่มีชื่อผู้รับบริการ HN AN ทำให้ไม่สามารถระบุได้...'),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='finding_sorting_issue',
            field=models.BooleanField(default=False, verbose_name='การจัดเรียงเวชระเบียนไม่เป็นไปตามมาตรฐานที่กำหนด'),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='overall_finding',
            field=models.CharField(blank=True, choices=[('inadequate', 'Documentation inadequate for meaningful review (ข้อมูลไม่เพียงพอสำหรับการทบทวน)'), ('no_issue', 'No significant medical recode issue identified (ไม่มีปัญหาสำคัญจากการทบทวน)'), ('certain_issue', 'Certain issue in question specify (มีปัญหาจากการทบทวนที่ต้องค้นต่อ ระบุ)')], default='no_issue', max_length=50, null=True, verbose_name='Overall finding (เลือกเพียง 1 ข้อ)'),
        ),
    ]
