# Generated by Django 5.2 on 2025-09-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0009_remove_patientscore_s10_remove_patientscore_s11_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientscore',
            name='title',
        ),
    ]
