# Generated by Django 5.2 on 2026-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0010_alter_opdscore_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdscore',
            name='certain_issue_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ระบุปัญหา (กรณีเลือก Certain issue)'),
        ),
    ]
