# Generated by Django 5.2 on 2025-09-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0010_remove_patientscore_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientscore',
            name='s1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='s9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], max_length=3),
        ),
    ]
