# Generated by Django 5.2 on 2025-09-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0011_alter_patientscore_s1_alter_patientscore_s2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientscore',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s7',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s8',
        ),
        migrations.RemoveField(
            model_name='patientscore',
            name='s9',
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('NA', 'NA')], default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='title',
            field=models.CharField(blank=True, default='แบบประเมินคุณภาพการดูแลผู้ป่วย (ชั่วคราว)', max_length=255, verbose_name='หัวข้อแบบประเมิน'),
        ),
        migrations.AlterField(
            model_name='patientscore',
            name='max_score',
            field=models.IntegerField(blank=True, default=108),
        ),
    ]
