# Generated by Django 5.2 on 2025-09-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRAapp', '0012_remove_patientscore_s1_remove_patientscore_s2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscore',
            name='s10_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s10_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s11_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s12_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s1_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s2_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s3_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s4_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s5_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s6_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s7_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s8_9_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_7_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_8_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscore',
            name='s9_9_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
